on: [push, pull_request]
name: CI
jobs:
  # ================
  # TEST JOB
  #   runs on every push and PR
  #   runs 2x3 times (see matrix)
  # ================
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build -v .
  # ================
  # RELEASE JOB
  #   runs after a success test
  #   only runs on push "v*" tag
  # ================
  goreleaser:
    name: goreleaser

    on:
      push:
        # run only against tags
        tags:
          - startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write
      # packages: write
      # issues: write

    jobs:
      goreleaser:
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          -
            name: Fetch all tags
            run: git fetch --force --tags
          -
            name: Set up Go
            uses: actions/setup-go@v2
            with:
              go-version: 1.18
          -
            name: Run GoReleaser
            uses: goreleaser/goreleaser-action@v2
            with:
              # either 'goreleaser' (default) or 'goreleaser-pro'
              distribution: goreleaser
              version: latest
              args: release --rm-dist
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
